compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: true

enableInlineHunks: true

nodeLinker: node-modules

npmRegistryServer: "${REGISTRY_URL:-https://registry.npmjs.org}"

plugins:
  - ./scripts/changeVersionBerryPlugin.cjs

unsafeHttpWhitelist:
  - "*.npmmirror.org"
  - "*.tencent.com"
