enableInlineBuilds: true

enableInlineHunks: true

nodeLinker: node-modules

npmRegistryServer: "${REGISTRY_URL:-https://registry.npmjs.org}"

unsafeHttpWhitelist:
  - "*.taobao.org"
  - "*.tencent.com"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
