enableInlineBuilds: true

enableInlineHunks: true

nodeLinker: node-modules

# npm：https://registry.npmjs.org
# yarn：https://registry.yarnpkg.com
# 淘宝镜像：https://registry.npmmirror.com
# 腾讯镜像：https://mirrors.cloud.tencent.com/npm
npmRegistryServer: "${REGISTRY_URL:-https://registry.npmjs.org}"

unsafeHttpWhitelist:
  - "*.npmmirror.org"
  - "*.tencent.com"
